### ISSUE TITLE
Please add option to save blank password

### ISSUE THREAD

**Issue by cheesewick** [ddawson/Saved-Password-Editor#25]
Currently when changing password to blank there is an error:

`Got an error:
  [JavaScript Error: "Can't add a login with a null or empty password." {file: "resource://gre/modules/LoginHelper.jsm" line: 238}]'[JavaScript Error: "Can't add a login with a null or empty password." {file: "resource://gre/modules/LoginHelper.jsm" line: 238}]' when calling method: [nsILoginManagerStorage::modifyLogin]
Did you try to create a duplicate login entry?`

I know that it prevents possible mistakes, but sometimes it's intentionally behaviour of the user.

**Comment by ddawson** [comment]
Sorry, but it's not up to me. That's how the password manager works: you can't have blank passwords. If you want it changed, you'll need to talk to the Mozilla devs, though I doubt you'll convince them to relax this restriction.
