### ISSUE TITLE
Context Menu Spam

### ISSUE THREAD

**Issue by pwd-github** [ddawson/Saved-Password-Editor#29]
It may be fall out from 57, but as things currently stand, SPE is spamming the context menu with items currently.

![spe-contextmenuspam](https://user-images.githubusercontent.com/203217/29002641-01a63b2e-7a9f-11e7-9573-34559319b225.png)

**Comment by ddawson** [comment]
On 08/06/2017 04:04 AM, Paul wrote:
>
> It may be fall out from 57, but as things currently stand, SPE is 
> spamming the context menu with items currently.
>

I don't see anything unexpected there. It just has the regular three 
"...login info" items that are supposed to be there in the current 
design (which has not changed for quite some time). Nothing else is from 
SPE. Are you saying you consider three items to be a spamming amount? If 
it's too much, then maybe I could consider folding them in to a submenu.

Is this, perhaps, showing up for what appears to be something other than 
a field in a login form? If so, that certainly should not happen. Please 
let me know.

**Comment by sabret00the** [comment]
These are just showing in the normal context menu of a page where as they should only show on the context of a form field.

**Comment by ddawson** [comment]
What version of Firefox? Also, if it is happening on specific pages, can you provide a link so I can reproduce?

**Comment by sabret00the** [comment]
The current Nightly of Firefox and it happens on this page. Right click on the left or right of the posts within this thread.

**Comment by ddawson** [comment]
Got it. That seems to indicate the frame script stopped working. That's what determines whether you're on a field or not.
